# Example config of a Gree climate component with a current temperature sensor
substitutions:
  name: "gree-climate-with-sensor"

esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap: 
    ssid: ${name}-AP
    password: !secret wifi_password
    ap_timeout: 3min
    
captive_portal:

logger:

api:
  encryption:
    key: !secret key_gree_climate_with_sensor

ota:
 
external_components:
  - source: github://dosdroid/ESPHome_Gree_AC
    components: [ gree ]

sensor:
  - platform: homeassistant
    id: current_temperature
    name: "Current Temperature"
    entity_id: sensor.my_ha_sensor_temperature
    state_class: measurement
    device_class: temperature
    accuracy_decimals: 1
    unit_of_measurement: °C

climate:
- platform: gree
  name: "HVAC Head with sensor"
  pin: GPIO4
  sensor: current_temperature
  visual:
      min_temperature: 10
      max_temperature: 30
      temperature_step:
        target_temperature: 1.0
        current_temperature: 0.1
